# Generated by Django 6.0.7 on 2026-08-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_activitylog"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsultationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=150)),
                ("phone", models.CharField(max_length=20)),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("education", "مشاوره درباره دوره\u200cهای آموزشی"),
                            ("registration", "ثبت\u200cنام در دوره"),
                            ("career", "مشاوره ورود به بازار کار"),
                            ("other", "سایر موارد"),
                        ],
                        max_length=30,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
            ],
        ),
    ]
