# Generated by Django 6.0.7 on 2026-08-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0008_course_show_on_home"),
        ("core", "0004_consultationrequest"),
        ("shop", "0011_order_tracking_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="پیشنهادات امروز", max_length=200)),
                ("description", models.CharField(blank=True, max_length=300)),
                ("discount_percent", models.PositiveIntegerField(default=20)),
                ("end_time", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "courses",
                    models.ManyToManyField(
                        blank=True, related_name="home_offers", to="academy.course"
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True, related_name="home_offers", to="shop.product"
                    ),
                ),
            ],
        ),
    ]
