# Generated by Django 6.0.7 on 2026-08-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_homeoffer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homeoffer",
            name="discount_percent",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
