# Generated by Django 6.0.7 on 2026-08-21 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discounts", "0001_initial"),
        ("services", "0008_servicedetail_barberservicedetailprice"),
    ]

    operations = [
        migrations.AddField(
            model_name="discountcode",
            name="services",
            field=models.ManyToManyField(
                blank=True, related_name="discount_codes", to="services.service"
            ),
        ),
        migrations.AlterField(
            model_name="discountcode",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("all", "همه"),
                    ("products", "محصولات"),
                    ("courses", "دوره\u200cها"),
                    ("services", "خدمات"),
                ],
                default="all",
                max_length=20,
            ),
        ),
    ]
