# Generated by Django 6.0.7 on 2026-08-21 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discounts", "0002_discountcode_services_alter_discountcode_target_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discountcode",
            name="target_type",
        ),
        migrations.AddField(
            model_name="discountcode",
            name="courses_all",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="discountcode",
            name="products_all",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="discountcode",
            name="services_all",
            field=models.BooleanField(default=False),
        ),
    ]
