# Generated by Django 6.0.7 on 2026-07-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="price",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
