# Generated by Django 6.0.7 on 2026-08-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reservation",
            "0007_reservation_customer_name_reservation_customer_phone_and_more",
        ),
        ("services", "0004_servicecategory_service_order_service_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="barbers",
            field=models.ManyToManyField(
                blank=True, related_name="services", to="reservation.barber"
            ),
        ),
    ]
