# Generated by Django 6.0.7 on 2026-08-15 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0008_reservation_deposit_amount_and_more"),
        ("services", "0005_service_barbers"),
    ]

    operations = [
        migrations.CreateModel(
            name="BarberServicePrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.PositiveIntegerField(default=0)),
                (
                    "barber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_prices",
                        to="reservation.barber",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="barber_prices",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "unique_together": {("barber", "service")},
            },
        ),
    ]
