# Generated by Django 6.0.7 on 2026-08-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0006_barberserviceprice"),
    ]

    operations = [
        migrations.AddField(
            model_name="barberserviceprice",
            name="duration",
            field=models.PositiveIntegerField(
                default=30, help_text="مدت خدمت به دقیقه"
            ),
        ),
    ]
