# Generated by Django 6.0.7 on 2026-08-20 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0010_reservation_paid_amount_and_more"),
        ("services", "0007_barberserviceprice_duration"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="services.service",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BarberServiceDetailPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.PositiveIntegerField(default=0)),
                (
                    "duration",
                    models.PositiveIntegerField(
                        default=10, help_text="مدت جزئیات به دقیقه"
                    ),
                ),
                (
                    "barber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_detail_prices",
                        to="reservation.barber",
                    ),
                ),
                (
                    "detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="barber_prices",
                        to="services.servicedetail",
                    ),
                ),
            ],
            options={
                "unique_together": {("detail", "barber")},
            },
        ),
    ]
