# Generated by Django 6.0.7 on 2026-07-28 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("users_access", models.BooleanField(default=False)),
                ("barbers_access", models.BooleanField(default=False)),
                ("services_access", models.BooleanField(default=False)),
                ("reservations_access", models.BooleanField(default=False)),
                ("courses_access", models.BooleanField(default=False)),
                ("shop_access", models.BooleanField(default=False)),
                ("orders_access", models.BooleanField(default=False)),
                ("comments_access", models.BooleanField(default=False)),
                ("messages_access", models.BooleanField(default=False)),
                ("reports_access", models.BooleanField(default=False)),
                ("settings_access", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_permission",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
