# Generated by Django 6.0.7 on 2026-08-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_productfeature_productspecification"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="related_products",
            field=models.ManyToManyField(
                blank=True, related_name="recommended_for", to="shop.product"
            ),
        ),
    ]
