# Generated by Django 6.0.7 on 2026-08-08 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_productcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_type",
            field=models.CharField(
                choices=[
                    ("self", "خودم تحویل می\u200cگیرم"),
                    ("other", "شخص دیگر تحویل می\u200cگیرد"),
                ],
                default="self",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="postal_code",
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="receiver_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="receiver_phone",
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "در انتظار پرداخت"),
                    ("paid", "پرداخت شده"),
                    ("sent", "ارسال شده"),
                    ("completed", "تکمیل شده"),
                    ("cancelled", "لغو شده"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
