# Generated by Django 6.0.7 on 2026-08-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_order_delivery_type_order_postal_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="show_on_home",
            field=models.BooleanField(default=False),
        ),
    ]
