# Generated by Django 6.0.7 on 2026-08-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_product_show_on_home"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="confirmation_sms_sent",
            field=models.BooleanField(default=False),
        ),
    ]
