# Generated by Django 6.0.7 on 2026-08-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_order_confirmation_sms_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="tracking_code",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
