# Generated by Django 6.0.7 on 2026-07-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0002_course_capacity_course_duration_course_end_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursefeature",
            name="description",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="coursefeature",
            name="icon",
            field=models.CharField(default="fa-solid fa-star", max_length=100),
        ),
        migrations.AlterField(
            model_name="coursefeature",
            name="title",
            field=models.CharField(default="", max_length=200),
        ),
    ]
