# Generated by Django 6.0.7 on 2026-07-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0003_coursefeature_description_coursefeature_icon_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="intro_pdf",
            field=models.FileField(blank=True, null=True, upload_to="course_pdf/"),
        ),
        migrations.AddField(
            model_name="course",
            name="intro_video",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="course",
            name="level",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="course",
            name="prerequisite",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[("open", "باز"), ("closed", "تکمیل ظرفیت")],
                default="open",
                max_length=20,
            ),
        ),
    ]
