# Generated by Django 6.0.7 on 2026-08-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0005_sessionprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursesession",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="course_files/"),
        ),
        migrations.AddField(
            model_name="coursesession",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coursesession",
            name="pdf",
            field=models.FileField(blank=True, null=True, upload_to="course_pdfs/"),
        ),
    ]
