# Generated by Django 6.0.7 on 2026-08-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0007_coursefavorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="show_on_home",
            field=models.BooleanField(default=False),
        ),
    ]
