# Generated by Django 6.0.7 on 2026-07-26 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reservation",
            "0002_alter_reservation_barber_alter_reservation_service_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="barber",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="reservation.barber",
            ),
        ),
    ]
