# Generated by Django 6.0.7 on 2026-07-26 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0003_alter_reservation_barber"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reservation",
            unique_together={("barber", "date", "time")},
        ),
    ]
