# Generated by Django 6.0.7 on 2026-07-27 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0004_alter_reservation_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="barber",
            name="appointment_duration",
            field=models.IntegerField(default=30, help_text="مدت هر نوبت (دقیقه)"),
        ),
        migrations.AddField(
            model_name="barber",
            name="work_end",
            field=models.TimeField(default="18:00"),
        ),
        migrations.AddField(
            model_name="barber",
            name="work_start",
            field=models.TimeField(default="09:00"),
        ),
        migrations.CreateModel(
            name="BarberDayOff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("reason", models.CharField(blank=True, max_length=200)),
                (
                    "barber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days_off",
                        to="reservation.barber",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BarberWorkingDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.IntegerField(
                        choices=[
                            (0, "شنبه"),
                            (1, "یکشنبه"),
                            (2, "دوشنبه"),
                            (3, "سه\u200cشنبه"),
                            (4, "چهارشنبه"),
                            (5, "پنجشنبه"),
                            (6, "جمعه"),
                        ]
                    ),
                ),
                ("is_working", models.BooleanField(default=True)),
                (
                    "barber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="working_days",
                        to="reservation.barber",
                    ),
                ),
            ],
            options={
                "unique_together": {("barber", "day")},
            },
        ),
    ]
