# Generated by Django 6.0.7 on 2026-08-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reservation",
            "0007_reservation_customer_name_reservation_customer_phone_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="deposit_amount",
            field=models.PositiveBigIntegerField(default=0, help_text="مبلغ بیعانه"),
        ),
        migrations.AddField(
            model_name="reservation",
            name="payment_reference",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "در انتظار پرداخت"),
                    ("paid", "پرداخت شده"),
                    ("failed", "ناموفق"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="service_price",
            field=models.PositiveBigIntegerField(
                default=0, help_text="قیمت خدمت در زمان رزرو"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "در انتظار پرداخت"),
                    ("approved", "تایید شده"),
                    ("done", "انجام شده"),
                    ("cancel", "لغو شده"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
