# Generated by Django 6.0.7 on 2026-08-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0008_reservation_deposit_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="reminder_sent",
            field=models.BooleanField(default=False),
        ),
    ]
