# Generated by Django 6.0.7 on 2026-08-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0009_reservation_reminder_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="paid_amount",
            field=models.PositiveBigIntegerField(
                default=0, help_text="مبلغ پرداخت شده"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "پرداخت نشده"),
                    ("deposit_paid", "بیعانه پرداخت شده"),
                    ("paid", "کامل پرداخت شده"),
                    ("failed", "پرداخت ناموفق"),
                    ("refunded", "مبلغ برگشت داده شده"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
