# Generated by Django 6.0.7 on 2026-08-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0010_reservation_paid_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="selected_details",
            field=models.JSONField(
                blank=True, default=list, help_text="جزئیات انتخاب شده هنگام رزرو"
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="total_duration",
            field=models.PositiveIntegerField(
                default=0, help_text="مدت کل خدمت به دقیقه"
            ),
        ),
    ]
