# Generated by Django 6.0.7 on 2026-08-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0011_reservation_selected_details_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="survey_sms_sent",
            field=models.BooleanField(default=False),
        ),
    ]
