# Generated by Django 6.0.7 on 2026-08-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0012_reservation_survey_sms_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="survey_token",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
