# Generated by Django 6.0.7 on 2026-08-29 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0014_appointmentreview"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="survey_sms_sent",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="survey_token",
        ),
        migrations.DeleteModel(
            name="AppointmentReview",
        ),
    ]
