# Generated by Django 6.0.7 on 2026-08-29 22:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0015_remove_reservation_survey_sms_sent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="survey_sms_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reservation",
            name="survey_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
